// Generated by tools/generate_ui_contract.py from ui/ui_spec.json. DO NOT EDIT.
#pragma once

#include <stdint.h>

namespace ui {
namespace spec {
constexpr uint32_t kContractVersion = 4;
constexpr int kCanvasWidth = 540;
constexpr int kCanvasHeight = 960;
constexpr int kPhysicalWidth = 960;
constexpr int kPhysicalHeight = 540;
constexpr int kFramebufferBitsPerPixel = 4;
constexpr int kFramebufferStrideBytes = 480;
constexpr int kMargin = 24;
constexpr int kGrid = 8;
constexpr int kAppBarHeight = 104;
constexpr int kNavHeight = 96;
constexpr int kContentBottom = 864;
constexpr int kMinimumTouchTarget = 56;
constexpr int kNavItemWidth = 108;
constexpr uint8_t kInk = 0x00;
constexpr uint8_t kInkMuted = 0x00;
constexpr uint8_t kRule = 0x00;
constexpr uint8_t kSurfaceStrong = 0xFF;
constexpr uint8_t kSurface = 0xFF;
constexpr uint8_t kSurfaceSoft = 0xFF;
constexpr uint8_t kPaper = 0xFF;
constexpr int kFontCaptionPixels = 15;
constexpr int kFontBodyPixels = 18;
constexpr int kFontCardHeadingPixels = 22;
constexpr int kFontPageHeadingPixels = 28;
constexpr int kFontBrandPixels = 32;
constexpr int kFontMetricPixels = 30;
constexpr int kFontNavigationPixels = 15;
constexpr int kTouchCornerX = 100;
constexpr int kTouchCornerY = 120;
constexpr int kTouchTargetInset = 84;
constexpr int kTouchTargetRadius = 44;
constexpr int kTouchMappingToleranceX = 70;
constexpr int kTouchMappingToleranceY = 100;
constexpr int kTouchTapSlop = 24;
constexpr int kTouchSwipeMin = 88;
constexpr int kTouchCrossAxisMax = 64;
constexpr int kTouchMinPressMs = 50;
constexpr int kTouchMaxPressMs = 1200;
constexpr int kTouchCleanReleaseMs = 500;
constexpr int kTouchTransitionCooldownMs = 500;
constexpr int kTouchPostRefreshQuietMs = 500;

constexpr int kHomeCardCount = 6;
constexpr int kHomeCards[kHomeCardCount][4] = {{24, 128, 492, 154}, {24, 306, 238, 112}, {278, 306, 238, 112}, {24, 434, 238, 112}, {278, 434, 238, 112}, {24, 562, 492, 252}};
constexpr int kSystemsCardCount = 2;
constexpr int kSystemsCards[kSystemsCardCount][4] = {{24, 144, 492, 326}, {24, 494, 492, 150}};
constexpr int kRadioCardCount = 3;
constexpr int kRadioCards[kRadioCardCount][4] = {{24, 128, 492, 156}, {24, 308, 492, 246}, {24, 580, 492, 210}};
constexpr int kLocationCardCount = 3;
constexpr int kLocationCards[kLocationCardCount][4] = {{24, 128, 492, 156}, {24, 310, 492, 246}, {24, 582, 492, 208}};
constexpr int kDeviceCardCount = 6;
constexpr int kDeviceCards[kDeviceCardCount][4] = {{24, 128, 238, 112}, {278, 128, 238, 112}, {24, 264, 492, 258}, {24, 550, 492, 88}, {24, 654, 492, 72}, {24, 742, 492, 72}};
constexpr int kDiagnosticsCardCount = 2;
constexpr int kDiagnosticsCards[kDiagnosticsCardCount][4] = {{24, 170, 492, 438}, {24, 632, 492, 158}};
constexpr int kSettingsCardCount = 5;
constexpr int kSettingsCards[kSettingsCardCount][4] = {{24, 128, 492, 148}, {24, 300, 492, 96}, {24, 420, 492, 96}, {24, 540, 492, 86}, {24, 650, 492, 96}};
constexpr int kTouchSetupCardCount = 3;
constexpr int kTouchSetupCards[kTouchSetupCardCount][4] = {{128, 160, 284, 142}, {128, 688, 284, 84}, {128, 790, 284, 128}};

}  // namespace spec
}  // namespace ui
