"""Generate the embedded C++ constants from the authoritative JSON UI contract."""
import json
from pathlib import Path

ROOT = Path(__file__).parents[1]
SPEC_PATH = ROOT / "ui" / "ui_spec.json"
HEADER_PATH = ROOT / "src" / "ui" / "ui_spec_generated.h"


def ident(name):
    return "".join(part.capitalize() for part in name.split("_"))


def render_header(spec):
    c, g, p, f, t = spec["canvas"], spec["geometry"], spec["palette"], spec["font"], spec["touch"]
    lines = [
        "// Generated by tools/generate_ui_contract.py from ui/ui_spec.json. DO NOT EDIT.",
        "#pragma once", "", "#include <stdint.h>", "", "namespace ui {", "namespace spec {",
        f"constexpr uint32_t kContractVersion = {spec['contract_version']};",
        f"constexpr int kCanvasWidth = {c['width']};", f"constexpr int kCanvasHeight = {c['height']};",
        f"constexpr int kPhysicalWidth = {c['physical_width']};", f"constexpr int kPhysicalHeight = {c['physical_height']};",
        f"constexpr int kFramebufferBitsPerPixel = {spec['framebuffer']['bits_per_pixel']};",
        f"constexpr int kFramebufferStrideBytes = {spec['framebuffer']['stride_bytes']};",
    ]
    for key, value in g.items():
        if isinstance(value, int):
            lines.append(f"constexpr int k{ident(key)} = {value};")
        elif isinstance(value, list) and len(value) == 4 and all(isinstance(item, int) for item in value):
            values = ", ".join(map(str, value))
            lines.append(f"constexpr int k{ident(key)}[4] = {{{values}}};")
    for key, value in p.items(): lines.append(f"constexpr uint8_t k{ident(key)} = 0x{value:02X};")
    for key, value in f["roles"].items():
        lines.append(f"constexpr int kFont{ident(key)}Pixels = {value};")
    for key, value in t.items(): lines.append(f"constexpr int kTouch{ident(key)} = {value};")
    lines.append("")
    for page, data in spec["pages"].items():
        name = ident(page)
        cards = ", ".join("{" + ", ".join(map(str, rect)) + "}" for rect in data["cards"])
        lines.append(f"constexpr int k{name}CardCount = {len(data['cards'])};")
        lines.append(f"constexpr int k{name}Cards[k{name}CardCount][4] = {{{cards}}};")
    lines += ["", "}  // namespace spec", "}  // namespace ui", ""]
    return "\n".join(lines)


def main():
    spec = json.loads(SPEC_PATH.read_text(encoding="utf-8"))
    # Generated source is normalized to LF even on Windows. Mixed newline
    # additions otherwise appear as trailing carriage-return whitespace to Git.
    with HEADER_PATH.open("w", encoding="utf-8", newline="\n") as output:
        output.write(render_header(spec))
    print(f"Generated {HEADER_PATH.relative_to(ROOT)} from {SPEC_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()