"""Generate deterministic final-size embedded glyphs from licensed font weights."""
import json
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
ROOT=Path(__file__).parents[1]; HEADER=ROOT/'src/ui/ui_fonts_generated.h'; METRICS=ROOT/'tools/ui_font_metrics.json'; CHARS=''.join(chr(c) for c in range(32,127))
ROLES={
 'Caption':('Inter-SemiBold.ttf',15,'reinforced_aa'),'Body':('Inter-SemiBold.ttf',18,'reinforced_aa'),'CardHeading':('Inter-SemiBold.ttf',22,'reinforced_aa'),
 'PageHeading':('Inter-Bold.ttf',28,'reinforced_aa'),'Brand':('Inter-Bold.ttf',32,'reinforced_aa'),'Metric':('Inter-Bold.ttf',30,'reinforced_aa'),
 'Navigation':('Inter-SemiBold.ttf',15,'reinforced_aa'),'QualificationCurrent':('AtkinsonHyperlegible-Regular.ttf',18,'mono'),
 'QualificationRegularAa':('Inter-Regular.ttf',18,'strong_aa'),'QualificationMediumAa':('Inter-Medium.ttf',18,'strong_aa'),
 'QualificationSemiboldAa':('Inter-SemiBold.ttf',20,'strong_aa'),'QualificationBoldMono':('Inter-Bold.ttf',20,'mono')}
def quantize(c,mode):
 if mode=='mono': return 15 if c>=112 else 0
 if mode=='reinforced_aa':
  if c>=128:return 15
  if c>=80:return 14
  if c>=48:return 13
  return 0
 if c>=192:return 15
 if c>=112:return 13
 if c>=72:return 11
 return 0
def pack(v): return [v[i]|((v[i+1] if i+1<len(v) else 0)<<4) for i in range(0,len(v),2)]
def generate(name,source_name,size,mode):
 source=ROOT/'assets/fonts'/source_name;font=ImageFont.truetype(str(source),size=size);asc,desc=font.getmetrics();glyphs=[];bitmap=[];black=ink=0
 for char in CHARS:
  left,top,right,bottom=font.getbbox(char,anchor='ls');w,h=max(0,right-left),max(0,bottom-top);offset=len(bitmap)
  if w and h:
   image=Image.new('L',(w,h),0);ImageDraw.Draw(image).text((-left,-top),char,font=font,fill=255,anchor='ls');coverage=[quantize(x,mode) for x in image.getdata()];bitmap.extend(pack(coverage));black+=sum(x==15 for x in coverage);ink+=sum(x>0 for x in coverage)
  glyphs.append((offset,w,h,left,top,max(1,round(font.getlength(char)))))
 return dict(name=name,source=source,size=size,mode=mode,ascent=asc,descent=desc,line_height=asc+desc,glyphs=glyphs,bitmap=bitmap,black=black,ink=ink)
def fmt(values,width=16): return '\n'.join('  '+', '.join(f'0x{x:02X}' for x in values[i:i+width])+',' for i in range(0,len(values),width))
def main():
 roles=[generate(n,*d) for n,d in ROLES.items()];lines=['// Generated by tools/generate_font_assets.py from Inter 4.1 and Atkinson Hyperlegible (OFL-1.1).','// Nibbles encode ink coverage; assets are rasterized at final physical size.','#pragma once','#include <stdint.h>','namespace ui::fonts {','struct Glyph { uint32_t offset; uint8_t width; uint8_t height; int8_t xOffset; int8_t yOffset; uint8_t advance; };','struct Font { const Glyph* glyphs; const uint8_t* bitmap; uint8_t ascent; uint8_t descent; uint8_t lineHeight; };']; metrics={'license':'OFL-1.1','rasterization':'final_size_no_scaling','roles':{}}
 for r in roles:
  s=r['name'];lines.append(f'static constexpr Glyph k{s}Glyphs[] = {{');lines.extend(f'  {{{o}, {w}, {h}, {x}, {y}, {a}}},' for o,w,h,x,y,a in r['glyphs']);lines+=['};',f'static constexpr uint8_t k{s}Bitmap[] = {{',fmt(r['bitmap']),'};',f"static constexpr Font k{s}{{k{s}Glyphs, k{s}Bitmap, {r['ascent']}, {r['descent']}, {r['line_height']}}};"]
  metrics['roles'][s]={'source':str(r['source'].relative_to(ROOT)).replace('\\','/'),'size':r['size'],'weight':r['source'].stem.split('-')[-1],'mode':r['mode'],'ascent':r['ascent'],'descent':r['descent'],'line_height':r['line_height'],'black_core_percent':round(100*r['black']/r['ink'],2) if r['ink'] else 0,'advances':[g[5] for g in r['glyphs']]}
 lines.append('}  // namespace ui::fonts');HEADER.write_text('\n'.join(lines)+'\n');METRICS.write_text(json.dumps(metrics,indent=2)+'\n');print(f'Generated {len(roles)} final-size weighted font assets')
if __name__=='__main__':main()
